version: '3'

services:
  server:
    container_name: gammaz
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - shared-data:/app/shared

  db:
    container_name: database
    image: postgres
    environment:
      - POSTGRES_DB=gammaz
      - POSTGRES_USER=sen
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - shared-data:/app/shared
    command: bash -c "cp /app/shared/gammaz.sql /docker-entrypoint-initdb.d/gammaz.sql && docker-entrypoint.sh postgres"

volumes:
  shared-data:
