version: '3'
services:

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8383:8383"
    volumes:
      - ./data:/app/data
    depends_on:
      - db
      
  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
      
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d
