version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    volumes:
      - ./data:/app/data
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "3307:5432"
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
